### ISSUE TITLE
Conform XML Output to Current Standard

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#29]
Current standard is outlined in the [wiki page](https://github.com/iTrace-Dev/iTrace-Core/wiki/iTrace-IDE-Plugin-XML-Format).

The plugin needs to follow the new standard and use like terminology for identifier/function names.

If this is already done and verified, the issue can be closed.

**Comment by clptrsn** [comment]
Updated to the new XML standard in commit 9130e971ee02d8e50c2992764eb59bfc244c9bda

**Comment by dtg3** [comment]
Looking at the most resent output the fields are all named correctly to the standard.
