### ISSUE TITLE
Enabling and Disabling Token Highlighting During Recording

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#35]
While I would not attempt this during any of the demos (with either of the plugins) we should make a decision whether this "feature" should be allowed. Currently, enabling and disabling during token highlighting throws and exception and halts the event id display in the status bar and stops token highlighting from working. Disconnecting and reconnecting seems to resolve the issue.

For now this is labeled as a bug as the controls are enabled and allow for this, but we could just as easily put in a guard for the user that disables the controls until the plugin is disconnected.

**Comment by dtg3** [comment]
@clptrsn @Zealot-311 Has this been addressed?

**Comment by clptrsn** [comment]
I could not reproduce the error happening. When I toggled the token highlighting the event id display did stop, but it stops if you click somewhere outside of the editor area which is a bug in of itself.

**Comment by dtg3** [comment]
I confirm that it still appears to token highlight even when the event id display stops. A new issue should be opened for that, but it's critical for the release.

**Comment by dtg3** [comment]
Created an issue for the event id display. This should be resolved now.
