### ISSUE TITLE
Eclipse Site Install Version Issue

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#37]
The currently posted eclipse update site [http://www.sdml.cs.kent.edu/itrace/alpha-0_1_0/itrace_eclipse/](http://www.sdml.cs.kent.edu/itrace/alpha-0_1_0/itrace_eclipse/) is displaying the wrong version numbers. All tooling versions should be `0.1.0`.

![versioning](https://user-images.githubusercontent.com/2080483/61822271-2b9a4980-ae27-11e9-91a8-a28bb4584349.png)

Also, what are the standards for the upper level naming group? Should it just say `iTrace Eclipse` instead of `Uncategorized`?

**Comment by shbonita** [comment]
@Zealot-311 are you dealing with this?

**Comment by dtg3** [comment]
This issue looks to be resolved.
