### ISSUE TITLE
iTrace Eclipse Licensing and Installer

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#38]
The licensing has a few issues:
1. It's GPL 2. I believe we discussed moving all stuff to GPL 3.
2. It still has YSU and SERS credited in the license
3. It contains the boiler plate text indicating what to change
4. The license file does not appear during the installation in eclipse, just some text that says `[Enter License Description here.]`

**Comment by dtg3** [comment]
If any of those points are invalid (like the switch to GPL 3), feel free to ignore them.

**Comment by shbonita** [comment]
@clptrsn can you please clean this up?

**Comment by clptrsn** [comment]
I switched to the GPL 3 license. Installer still needs to be updated to use it @Zealot-311

**Comment by dtg3** [comment]
New installer has a license, but the installer is showing the old GPL v2.

**Comment by dtg3** [comment]
I can verify the GPL 3 license appears in the development branch.
The old license in the installer site appears to be the result building off of the master branch instead of development. Issue can be closed.
