### ISSUE TITLE
Add User Facing Documentation to a Wiki Page

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#40]
How to change port number, installation (how to add an install site/plugin to eclipse), run with core.

**Comment by clptrsn** [comment]
The wiki should be up to date now and contains the same amount of information as the visual studio plugin

**Comment by dtg3** [comment]
Since the documentation is very similar to the content in the VS Wiki, please look over the critiques recently posted to that issue as some of the same items may apply. Once that's done, I'll look it over again.

**Comment by clptrsn** [comment]
Updated the wiki to account for the suggested changes

**Comment by dtg3** [comment]
Will the plugin work with any edition (Java, Java EE, C/C++, etc.) of eclipse?

**Comment by clptrsn** [comment]
I believe it will work on any edition. But not every version.

**Comment by clptrsn** [comment]
I will test later today

**Comment by dtg3** [comment]
"Photon" doesn't seem to be the default download option. It has a splash screen that says 2019.6. I'm trying the JEE edition now.

**Comment by dtg3** [comment]
I've made some changes to the documentation as well. If anything looks out of place, is incorrect, or doesn't read well feel free to edit.

**Comment by clptrsn** [comment]
For the data output files, there is a link to the Core github which is not public facing information.

**Comment by dtg3** [comment]
That content will be made accessible via the webpage when it is copied over. This is the compromise until we open the repos publicly.
