### ISSUE TITLE
Socket Settings does not work on the current Eclipse plugin installer site

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#41]
While reading over the instructions and following along I observed this bug:
![eclipse_plugin_issue](https://user-images.githubusercontent.com/2080483/62322175-7133c380-b472-11e9-9dad-1415ff4990cd.png)

**Comment by shbonita** [comment]
why does it still show the old workspace? @clptrsn can you look into fixing this?

**Comment by clptrsn** [comment]
I hadn’t updated the naming scheme since I didn’t see any user facing thing using it. I didn’t account for errors though

**Comment by shbonita** [comment]
Even if users don't see it, the naming needs updating. What are the options you have for it?

**Comment by clptrsn** [comment]
I can update it later tonight.

**Comment by clptrsn** [comment]
Or right now. Naming is updated as of 00eaa5ca7b9204b10b3a229d92bd337752971220

org.itrace is now the prefix used for the iTrace eclipse plugin namespace

**Comment by dtg3** [comment]
This appears to be a by product of the created install site being based from the master and not development branch. The iTrace namespace has also been updated so this issue should be able to be closed.
