### ISSUE TITLE
Extra Eclipse Plugin Controls on Plugin Window

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#42]
There still appear to be extra controls on the iTrace Eclipse plugin window:
![controls](https://user-images.githubusercontent.com/2080483/62323881-45b2d800-b476-11e9-9ceb-c3a747c98ee3.png)

* Reticle checkbox is not necessary as the Core does this
* XML Export checkbox is not needed as that is the only output format
* Open output file button (ellipsis button) doesn't need to be there as the Core provides data paths

At this stage of the game I would simply say hide the controls.

**Comment by clptrsn** [comment]
Is this off the installer version?
I think that code is based off the master version. The development is up to date and gets rid of this button

Should we merge development into master at this point anyway. It might make the installers easier to make

**Comment by clptrsn** [comment]
The XML export button is in development. I can remove that tonight

**Comment by dtg3** [comment]
Yes, I'm testing eclipse from the installation site and the installers should have been based off development. @Zealot-311 can you weigh in on what branch conatins the installer stuff or the branch it is based on?

@clptrsn it will need to be merged eventually, but it would be best if the process was done in development and merged into master (less likely to create a merge conflict depending on what files the installation site process involves).

**Comment by dtg3** [comment]
@clptrsn Just pulled and built development (HEAD commit is 00eaa5ca7b9204b10b3a229d92bd337752971220):
![plugin_controls](https://user-images.githubusercontent.com/2080483/62383005-d04e1280-b51c-11e9-8bcc-10c673aea032.png)

XML Export checkbox and file browser button (...) are still present.

**Comment by clptrsn** [comment]
Removed in 2e6a19a27b8c1ad17814a984b8b36b7e1957fa45

**Comment by dtg3** [comment]
I can verify the extra controls are no longer present on the form. Will test tomorrow with trackers to check for regressions.

**Comment by dtg3** [comment]
Does not appear to introduce regression.
