### ISSUE TITLE
Token Highlighting Performance

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#44]
Running from both the last working installer or building from source, the highlighting performance isn't great. I think while staring at a large tightly packed section of text it highlighted one token very briefly and then no others for a fair bit of time. I testing using the Gazepoint and even enlarged the font significantly. The Tobii however seemed to fair better. Can anyone confirm similar behavior?

**Comment by dtg3** [comment]
So while tracking with the reticle on I noticed that the Gazepoint tended to drift and overall was less steady. The highlighting improved subtly at 60Hz compared to 150Hz. This could be an issue with the calibration, but the reticle did pass over tokens and only occasionally would they be highlighted.

**Comment by dtg3** [comment]
The gif capturing tool didn't capture the token highlighting overlay. Our built in screen recording tool however did the job very nicely. Since the AVI's are decently large, I've placed them in a folder called `Eclipse_Plugin_Issue_44` in the iTrace folder on Google Drive. These show token highlighting performance of the three trackers (Mouse, Tobii, and Gazepoint) on the same line and same file.

All captures were using AbstractAction.java from JHotDraw8, observing content on line 21:
`public abstract class AbstractAction extends AbstractDisableable implements Action {`

Mouse feels a bit sluggish (perhaps because the mouse pointer provides instant positional feedback), the Tobii seems to perform best overall, and GazePoint was kind of abysmal.

This could simply be do to the performance difference between the trackers, but if I only had a GazePoint tracker, I might be inclined to think something is wrong.

If this is a non-issue, then we can close this issue and ship it as is.

**Comment by dtg3** [comment]
Based on feedback here and in issue #44 we need to decide if we are shipping this feature or not for the current release.

**Comment by dtg3** [comment]
Per Discord discussion, the token highlighted feature will be included in the 0.1.0 release.

**Comment by clptrsn** [comment]
The token highlighter is a lot more responsive now
