### ISSUE TITLE
Eclipse Plugin is Holding Output Files Open

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#45]
Files are unable to be moved/deleted as long as the plugin in running after starting a tracking activity.

Steps to reproduce:
1) Build Plugin from Source
2) Connect eclipse plugin to Core
3) Start tracking w/ Core
4) Stop tracking w/ Core
5) Disconnect plugin
6) Attempt to move/delete data file (it should say file in use by Java)
7) Close Eclipse environment
8) Attempt to move/delete data file (should work now)

It's not a deal breaker, but it is annoying (thus the medium priority).

**Comment by dtg3** [comment]
File is also not released when starting another recording session. The results is both files are still locked "in use".

**Comment by clptrsn** [comment]
Fixed in 879914ecd8ac35db57aa84d5068b154fb9fc8c65
Underlying stream was not closed when the xml writer was closed. Added the closing of the stream in the dispose method

**Comment by dtg3** [comment]
Works in the latest provided installer site. Files can be deleted or moved as long as plugin is disconnected.
