### ISSUE TITLE
Eclipse is sending zero based col positions

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#46]
Per discussions in meetings and Issue 6 in Post Processing all plugins must output line/col data as one based positions. This means the first character in the first line of the file is located at position should be recorded as line=1 col=1.

Presently Eclipse is outputting line=1 col=0

**Comment by clptrsn** [comment]
Fixed in c6eb85d8c95e975f4558a22ce4d7f43c3ac102c4

**Comment by dtg3** [comment]
Verified fixed using mouse tracker (only real way to get a precise position) in the most recently provided installer site.
