### ISSUE TITLE
Update GPL3 License Fields

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#48]
On the GPL3 license there are fill in locations indicated  with <...>  where the ellipsis is the content that is supposed to be written there such as <year>, <name of author>, <program>, etc. All affiliation information can be simply iTrace (as though it were a company) the rest should be self explanatory.  An issue will be made concerning this on GitHub.

This should take place on the license file in the repo and the license file shown during plugin installation.

**Comment by clptrsn** [comment]
Fixed in ef1ca54b9a8938619371563231a21bc5afd22538

**Comment by dtg3** [comment]
Verified fixed in the last provided installer site.
