### ISSUE TITLE
Highlight for Token can Remain on Screen

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#49]
If token highlighting is enabled during tracking and a token is highlighted while the tracker is stopped by highlighting remains checked, the token's highlight box will remain visible and affixed to the position on the screen even during scrolling until the window is closed.

If a similar situation occurs however token highlighting is unchecked. Interacting with the window will remove the highlighting (redraw the window without it).

**Comment by dtg3** [comment]
This is probably not a blocking issue for the release, but should be noted for subsequent releases.

**Comment by clptrsn** [comment]
With this and issue #44. I’m going to gut out and rewrite the highlighting engine once I get time. I’ve been unhappy with it for the past few months and have done my best to patch it but I think a more straight forward implementation exists and will investigate that

**Comment by dtg3** [comment]
Long term this sounds like a good idea.

Short term, the question becomes do we cut it out for this release or leave it in?

**Comment by dtg3** [comment]
Per Discord discussion, short term will be to release alpha 0.1.0 with the inclusion of the feature.

**Comment by shbonita** [comment]
related to #44

**Comment by clptrsn** [comment]
Token highlighting is a lot more responsive now with the recent PR
