### ISSUE TITLE
Connect to Core Button Can Shrink

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#50]
On some occasions, the `Connect to Core` button will shrink in size to accommodate the `Disconnect` text but not resize to fix the `Connect to Core` text.

**Comment by clptrsn** [comment]
I haven't run into the issue, but since the issue only pops up occasionally, additional testing is required

**Comment by dtg3** [comment]
Seems alright.

One thing that might be beneficial would be to test this again next time someone creates an installer. If I recall correctly, that was the only time I noticed that behavior.

For now though since the code is already in Development and seems stable I say the issue can be closed.
