### ISSUE TITLE
Button Text for Connecting

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#52]
The button text for connecting on the plugin currently reads `Connect to Server`. It should really say `Connect to Core`.

**Comment by dtg3** [comment]
Documentation will need to be updated to match when the change is complete.

**Comment by shbonita** [comment]
@clptrsn are you picking this up?

**Comment by dtg3** [comment]
After testing the latest release package provided by @Zealot-311. The button text remained unchanged.

**Comment by clptrsn** [comment]
I’ll take a look and get it fixed
