### ISSUE TITLE
Automatic Installer Generation

### ISSUE THREAD

**Issue by Zealot-311** [iTrace-Dev/iTrace-Eclipse#55]
Create automation to automatically update the update site.

**Comment by dtg3** [comment]
Related to discussion in issue #47

**Comment by Zealot-311** [comment]
Instead of doing a whole automation process, we're thinking that we'll just stick with the copy-paste method. I will further flesh out the step-by-step for this process in the wiki, adding pictures and double checking that the method works as intended.

**Comment by shbonita** [comment]
@fisherdog1 @KangilPark please check this.

**Comment by KangilPark** [comment]
Not needed at this time as we are not automating the installer generation process at the moment.
