### ISSUE TITLE
Error thrown when opening plaintext files when tracking

### ISSUE THREAD

**Issue by clptrsn** [iTrace-Dev/iTrace-Eclipse#58]
Steps to reproduce
1. Open a project with a .txt file in it
2. Start Tracking with iTrace Eclipse and Core
3. Open the .txt file. The following image should be shown
![image](https://user-images.githubusercontent.com/8206100/109433750-a64e2200-79d7-11eb-8958-5e486167b9d0.png)

The tracking does not work on the plaintext file but will work after the file is closed and iTrace Eclipse will proceed as normal

**Comment by KangilPark** [comment]
The error can be avoided by disabling the use of ProjectionViewer and changing the foldedLineIndex to lineIndex.

**Comment by shbonita** [comment]
@clptrsn I've assigned this one to you to fix. We came across this while testing @KangilPark version of iTrace.

**Comment by KangilPark** [comment]
In development branch make sure code folding is enabled and provides the proper values.

**Comment by KangilPark** [comment]
Closing as issue is related to #64
